[package]
name = "oxitest"
version = "1.0.0-beta.1"
edition = "2021"
license = "MIT"

[lib]
name = "_oxitest"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.29"
ignore = "0.4"
toml = "1.1"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
thiserror = "2"
globset = "0.4"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = { version = "1", features = ["raw_value"] }
console = "0.16"
indicatif = "0.18"
indexmap = "2"
logos = "0.16"
miette = { version = "7", features = ["fancy-no-backtrace"] }
parking_lot = "0.12"
ahash = { version = "0.8", features = ["serde"] }
crossbeam-channel = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
camino = "1"
rand = "0.10.1"
similar = "3"
quick-xml = { version = "0.40", features = ["serialize"] }
rustpython-parser = "0.4"
rayon = "1"
regex = "1"

[dev-dependencies]
tempfile = "3"
assert_fs = "1"
insta = { version = "1", features = ["redactions"] }

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"

[lints.clippy]
all = "deny"
